import equivalentsSeed from "../../seed/equivalents.json";

/**
 * Foreign-brand paint code → Tamiya code, compiled into the build for the
 * same reasons as the paint catalogue itself (`./paints.ts`) — a lookup a
 * paint-extraction call needs synchronously has no business costing a round
 * trip. Source: `seed/equivalents.json`, generated by
 * `scripts/build-equivalents.ts` from the Cybermodeler Tamiya Color
 * Cross-Reference (docs/PLAN.md §2.2, Phase 5).
 *
 * A code sometimes maps to more than one Tamiya paint — a shade often has
 * both a bottle code and a spray-can code (Mr. Color C335 is both Tamiya
 * AS-11 and XF-83, the spray and bottle versions of the same Medium Sea
 * Gray). `resolveForeignCode` has to return one, since the thing calling it
 * (`domain/kit-paint-extraction.ts`) wants a single `paintCode`, so it
 * prefers the bottle/lacquer form (X, XF, LP) over a spray can (TS, AS) —
 * that's the format the Thinner Bench's own ratio calculator is built
 * around, and it's the more broadly useful "buy this" answer when someone
 * owns neither. A caller that genuinely needs every candidate, not just the
 * preferred one, should read `seed/equivalents.json` directly rather than
 * extend this function's return shape for a need that doesn't exist yet.
 */

interface SeedEquivalent {
  brand: string;
  foreign_code: string;
  foreign_name: string | null;
  tamiya_code: string;
  match_quality: string;
  source: string;
}

const SPRAY_LINES = new Set(["TS", "AS"]);

function linePrefix(code: string): string {
  return code.split("-")[0];
}

/** Normalizes a foreign code for lookup — not `normalizePaintCode` (that
 * inserts a Tamiya-style "LETTERS-NUMBER" hyphen these codes don't follow:
 * "UA507", "MMP049", "32167" aren't shaped like "XF-64"). Just enough to
 * match on the code as printed, case- and whitespace-insensitively. */
function foreignKey(raw: string): string {
  return raw.toUpperCase().replace(/\s+/g, "");
}

const BY_FOREIGN_CODE = new Map<string, string[]>();
for (const e of equivalentsSeed as SeedEquivalent[]) {
  const key = foreignKey(e.foreign_code);
  const candidates = BY_FOREIGN_CODE.get(key);
  if (candidates) {
    if (!candidates.includes(e.tamiya_code)) candidates.push(e.tamiya_code);
  } else {
    BY_FOREIGN_CODE.set(key, [e.tamiya_code]);
  }
}

/** A foreign-brand code (any brand — the caller doesn't know which one a
 * manual meant, and in practice a code is unambiguous regardless) to its
 * best single Tamiya equivalent, or `null` if this chart has no row for it.
 * Accepts the same loose input `getCataloguePaint` does. */
export function resolveForeignCode(raw: string): string | null {
  const candidates = BY_FOREIGN_CODE.get(foreignKey(raw));
  if (!candidates) return null;
  return candidates.find((code) => !SPRAY_LINES.has(linePrefix(code))) ?? candidates[0];
}

export const CATALOGUE_EQUIVALENTS_SIZE = (equivalentsSeed as SeedEquivalent[]).length;
