import brandsSeed from "../../seed/paint-brands.json";
import equivalentsSeed from "../../seed/equivalents.json";

/**
 * Foreign-brand paint code → Tamiya code, compiled into the build for the
 * same reasons as the paint catalogue itself (`./paints.ts`) — a lookup a
 * paint-extraction call needs synchronously has no business costing a round
 * trip. Source: `seed/equivalents.json`, generated by
 * `scripts/build-equivalents.ts` from the Cybermodeler Tamiya Color
 * Cross-Reference (docs/PLAN.md §2.2, Phase 5).
 *
 * A code sometimes maps to more than one Tamiya paint — a shade often has
 * both a bottle code and a spray-can code (Mr. Color C335 is both Tamiya
 * AS-11 and XF-83, the spray and bottle versions of the same Medium Sea
 * Gray). `resolveForeignCode` has to return one, since the thing calling it
 * (`domain/kit-paint-extraction.ts`) wants a single `paintCode`, so it
 * prefers the bottle/lacquer form (X, XF, LP) over a spray can (TS, AS) —
 * that's the format the Thinner Bench's own ratio calculator is built
 * around, and it's the more broadly useful "buy this" answer when someone
 * owns neither.
 *
 * The reverse direction — one Tamiya code to every brand that sells a match —
 * is `getEquivalentsFor` at the bottom of this file. That need did not exist
 * when this file was written (the note here used to say so); the Thinner
 * Bench's "Also sold as" card created it, and both directions belong in one
 * module reading one seed file rather than two half-indexes of the same data.
 */

interface SeedEquivalent {
  brand: string;
  foreign_code: string;
  foreign_name: string | null;
  tamiya_code: string;
  match_quality: string;
  source: string;
}

const SPRAY_LINES = new Set(["TS", "AS"]);

function linePrefix(code: string): string {
  return code.split("-")[0];
}

/** Normalizes a foreign code for lookup — not `normalizePaintCode` (that
 * inserts a Tamiya-style "LETTERS-NUMBER" hyphen these codes don't follow:
 * "UA507", "MMP049", "32167" aren't shaped like "XF-64"). Just enough to
 * match on the code as printed, case- and whitespace-insensitively. */
function foreignKey(raw: string): string {
  return raw.toUpperCase().replace(/\s+/g, "");
}

const BY_FOREIGN_CODE = new Map<string, string[]>();
for (const e of equivalentsSeed as SeedEquivalent[]) {
  const key = foreignKey(e.foreign_code);
  const candidates = BY_FOREIGN_CODE.get(key);
  if (candidates) {
    if (!candidates.includes(e.tamiya_code)) candidates.push(e.tamiya_code);
  } else {
    BY_FOREIGN_CODE.set(key, [e.tamiya_code]);
  }
}

/** A foreign-brand code (any brand — the caller doesn't know which one a
 * manual meant, and in practice a code is unambiguous regardless) to its
 * best single Tamiya equivalent, or `null` if this chart has no row for it.
 * Accepts the same loose input `getCataloguePaint` does. */
export function resolveForeignCode(raw: string): string | null {
  const candidates = BY_FOREIGN_CODE.get(foreignKey(raw));
  if (!candidates) return null;
  return candidates.find((code) => !SPRAY_LINES.has(linePrefix(code))) ?? candidates[0];
}

export const CATALOGUE_EQUIVALENTS_SIZE = (equivalentsSeed as SeedEquivalent[]).length;

// ---------------------------------------------------------------------------
// Tamiya → foreign, for the Thinner Bench's "Also sold as" card
// ---------------------------------------------------------------------------

interface SeedBrand {
  key: string;
  label: string;
  sort: number;
}

export interface BrandEquivalents {
  brandKey: string;
  /** "Gunze/Mr. Hobby", "AMMO by Mig" — from `seed/paint-brands.json`. */
  label: string;
  /** Every code this brand sells that matches, in the order the chart lists
   * them: Mr. Color's C/H/N ranges are the same shade in three product lines,
   * and which one is on the shelf differs by shop. */
  codes: string[];
}

const BRANDS = new Map((brandsSeed as SeedBrand[]).map((b) => [b.key, b]));

/**
 * Brand display order is `sort` from `seed/paint-brands.json` — the call
 * documented in docs/PLAN.md §2.2: Gunze first because Japanese car kits call
 * Mr. Color throughout, Revell second because Revell kits fill European
 * shops. It is data, so re-ordering it is a seed edit, not a code change.
 */
const BY_TAMIYA_CODE = new Map<string, BrandEquivalents[]>();
for (const e of equivalentsSeed as SeedEquivalent[]) {
  const brand = BRANDS.get(e.brand);
  // A brand missing from the seed is a CI failure in `verify-catalogue.ts`,
  // not something to render — skip rather than invent a label for it.
  if (!brand) continue;

  const groups = BY_TAMIYA_CODE.get(e.tamiya_code) ?? [];
  const existing = groups.find((g) => g.brandKey === e.brand);
  if (existing) {
    if (!existing.codes.includes(e.foreign_code)) existing.codes.push(e.foreign_code);
  } else {
    groups.push({ brandKey: e.brand, label: brand.label, codes: [e.foreign_code] });
  }
  BY_TAMIYA_CODE.set(e.tamiya_code, groups);
}

for (const groups of BY_TAMIYA_CODE.values()) {
  groups.sort((a, b) => (BRANDS.get(a.brandKey)?.sort ?? 0) - (BRANDS.get(b.brandKey)?.sort ?? 0));
}

/**
 * Every brand that sells a match for this Tamiya code, in display order —
 * empty when the chart has no row for it, which is common and not an error.
 * Coverage is uneven by line: the bottle ranges are well covered, the TS/AS
 * spray cans barely at all, so a decanted spray usually returns nothing.
 */
export function getEquivalentsFor(tamiyaCode: string): BrandEquivalents[] {
  return BY_TAMIYA_CODE.get(tamiyaCode) ?? [];
}
