import brandsSeed from "../../seed/paint-brands.json";
import equivalentsSeed from "../../seed/equivalents.json";

/**
 * Foreign-brand paint code → Tamiya code, compiled into the build for the
 * same reasons as the paint catalogue itself (`./paints.ts`) — a lookup a
 * paint-extraction call needs synchronously has no business costing a round
 * trip. Source: `seed/equivalents.json`, generated by
 * `scripts/build-equivalents.ts` from the Cybermodeler Tamiya Color
 * Cross-Reference (docs/PLAN.md §2.2, Phase 5).
 *
 * A code sometimes maps to more than one Tamiya paint — a shade often has
 * both a bottle code and a spray-can code (Mr. Color C335 is both Tamiya
 * AS-11 and XF-83, the spray and bottle versions of the same Medium Sea
 * Gray), and the Gunze codes typically offer an acrylic and a lacquer.
 * `resolveForeignCode` has to return one, since the thing calling it
 * (`domain/kit-paint-extraction.ts`) wants a single `paintCode`; which one,
 * and why it is not simply the chart's first row, is `LINE_PREFERENCE`
 * below.
 *
 * The reverse direction — one Tamiya code to every brand that sells a match —
 * is `getEquivalentsFor` at the bottom of this file. That need did not exist
 * when this file was written (the note here used to say so); the Thinner
 * Bench's "Also sold as" card created it, and both directions belong in one
 * module reading one seed file rather than two half-indexes of the same data.
 */

interface SeedEquivalent {
  brand: string;
  foreign_code: string;
  foreign_name: string | null;
  tamiya_code: string;
  match_quality: string;
  source: string;
}

/**
 * Which Tamiya line to prefer when the chart offers several for one foreign
 * code, best first.
 *
 * The chart's own row order is not a preference, it is just the order
 * Cybermodeler happens to list things in, and taking "the first one that
 * isn't a spray can" from it put **LP** — the lacquer line — ahead of X/XF
 * on every Gunze code that has both. That is the wrong answer for the
 * question this app asks. `X`/`XF` is the acrylic range the shelf is stocked
 * from (§2.1: 29 of 33 bottles) and the one the Thinner Bench's ratio rules
 * are built around; LP is a different product needing different thinner.
 * Resolving `H8` to `LP-11` when `X-11` is in the rack doesn't just pick an
 * odd synonym — it reports a paint you own as one you have to go and buy,
 * which is precisely the mistake the Owned/Missing split exists to prevent.
 *
 * Sprays stay last, for the reason the old rule had them last: a decanted
 * TS/AS can is a real way to get a colour, but it is the awkward one, and
 * "buy this" should name a bottle whenever a bottle exists.
 */
const LINE_TIERS = [
  ["X", "XF"], // acrylic bottles — the shelf's own format
  ["LP"], // lacquer bottles: a bottle, but a different product and thinner
  ["PS", "TS", "AS"], // spray cans, decanted at best
];

const LINE_RANK = new Map(
  LINE_TIERS.flatMap((lines, tier) => lines.map((line) => [line, tier] as const)),
);

/**
 * Lower is better; an unknown line sorts last rather than throwing.
 *
 * `X` and `XF` deliberately share a tier. They are the same product in
 * different finishes — gloss and flat — not a better and a worse option, and
 * ranking one above the other silently answers a question about finish with a
 * preference about nothing. It really did: with X above XF, adding a second
 * source flipped C64 from XF-4 (flat) to X-15 (gloss) purely on that ordering.
 * Tied here, the choice falls to corroboration and then to chart order, so a
 * new source has to be *agreed with* to override an existing answer rather
 * than merely arriving.
 */
function lineRank(code: string): number {
  return LINE_RANK.get(code.split("-")[0]) ?? LINE_TIERS.length;
}

/** Normalizes a foreign code for lookup — not `normalizePaintCode` (that
 * inserts a Tamiya-style "LETTERS-NUMBER" hyphen these codes don't follow:
 * "UA507", "MMP049", "32167" aren't shaped like "XF-64").
 *
 * Case and whitespace, and then the one difference that actually breaks
 * matching in practice: **zero padding**. Cybermodeler writes Gunze's codes
 * padded to three digits — `H004`, `C068` — and no bottle, box or manual
 * does. A Japanese kit calls out `H4`, which is the exact case this chart
 * exists to serve, and it missed every one of them until this was fixed
 * (docs/PLAN.md §7).
 *
 * The padding is only stripped from a LETTERS+DIGITS code, never a bare
 * numeric one. That restriction is the whole safety argument: this index is
 * deliberately brand-agnostic (see `resolveForeignCode`), and the codes that
 * are *only* digits are the ones that genuinely collide across brands —
 * AMMO's `0032` and Mr. Paint's `032` are different paints, and un-padding
 * them merges Gloss White into Flat Aluminium. With the letter prefix
 * required, the chart's 713 distinct keys stay 713.
 */
function foreignKey(raw: string): string {
  const key = raw.toUpperCase().replace(/\s+/g, "");
  const prefixed = /^([A-Z]+)0*(\d+)$/.exec(key);
  return prefixed ? `${prefixed[1]}${prefixed[2]}` : key;
}

interface Candidate {
  code: string;
  /** Listed by both source charts (`match_quality: "confirmed"`, set in
   * scripts/build-equivalents.ts). Two independent references agreeing beats
   * either one alone, so these win before the line preference is consulted. */
  confirmed: boolean;
  /** 0 if Cybermodeler carries this pair, 1 if only mech9 does — the final
   * tiebreak, see `isBetter`. */
  sourceRank: number;
}

const BY_FOREIGN_CODE = new Map<string, Candidate[]>();
for (const e of equivalentsSeed as SeedEquivalent[]) {
  const key = foreignKey(e.foreign_code);
  const confirmed = e.match_quality === "confirmed";
  const sourceRank = e.source.includes("cybermodeler") ? 0 : 1;
  const candidates = BY_FOREIGN_CODE.get(key);
  if (!candidates) {
    BY_FOREIGN_CODE.set(key, [{ code: e.tamiya_code, confirmed, sourceRank }]);
    continue;
  }
  const existing = candidates.find((c) => c.code === e.tamiya_code);
  if (existing) {
    existing.confirmed ||= confirmed;
    existing.sourceRank = Math.min(existing.sourceRank, sourceRank);
  } else {
    candidates.push({ code: e.tamiya_code, confirmed, sourceRank });
  }
}

/** A foreign-brand code (any brand — the caller doesn't know which one a
 * manual meant, and in practice a code is unambiguous regardless) to its
 * best single Tamiya equivalent, or `null` if this chart has no row for it.
 * Accepts the same loose input `getCataloguePaint` does. */
export function resolveForeignCode(raw: string): string | null {
  const candidates = BY_FOREIGN_CODE.get(foreignKey(raw));
  if (!candidates) return null;
  // Corroboration first, line preference second; strictly-better keeps the
  // chart's own order as the final tiebreak.
  return candidates.reduce((best, c) => (isBetter(c, best) ? c : best)).code;
}

/**
 * Corroboration, then product tier, then the incumbent source.
 *
 * That last step is a change-control rule, and it needs stating because the
 * alternative is silent. `seed/equivalents.json` is sorted by Tamiya code, so
 * without an explicit tiebreak a tie is settled *alphabetically* — which is
 * how adding mech9 first flipped fifteen existing answers, none of them for
 * any better reason than `X-15` sorting before `XF-4`.
 *
 * So a second source has to earn an override: either both charts agree, or it
 * offers a better product tier (a bottle where the incumbent had a spray can).
 * Absent either, the answer that was already being used stands.
 */
function isBetter(a: Candidate, b: Candidate): boolean {
  if (a.confirmed !== b.confirmed) return a.confirmed;
  if (lineRank(a.code) !== lineRank(b.code)) return lineRank(a.code) < lineRank(b.code);
  return a.sourceRank < b.sourceRank;
}

// ---------------------------------------------------------------------------
// Tamiya → foreign, for the Thinner Bench's "Also sold as" card
// ---------------------------------------------------------------------------

interface SeedBrand {
  key: string;
  label: string;
  sort: number;
}

export interface BrandEquivalents {
  brandKey: string;
  /** "Gunze/Mr. Hobby", "AMMO by Mig" — from `seed/paint-brands.json`. */
  label: string;
  /** Every code this brand sells that matches, in the order the chart lists
   * them: Mr. Color's C/H/N ranges are the same shade in three product lines,
   * and which one is on the shelf differs by shop. */
  codes: string[];
}

const BRANDS = new Map((brandsSeed as SeedBrand[]).map((b) => [b.key, b]));

/**
 * Brand display order is `sort` from `seed/paint-brands.json` — the call
 * documented in docs/PLAN.md §2.2: Gunze first because Japanese car kits call
 * Mr. Color throughout, Revell second because Revell kits fill European
 * shops. It is data, so re-ordering it is a seed edit, not a code change.
 */
const BY_TAMIYA_CODE = new Map<string, BrandEquivalents[]>();
for (const e of equivalentsSeed as SeedEquivalent[]) {
  const brand = BRANDS.get(e.brand);
  // A brand missing from the seed is a CI failure in `verify-catalogue.ts`,
  // not something to render — skip rather than invent a label for it.
  if (!brand) continue;

  const groups = BY_TAMIYA_CODE.get(e.tamiya_code) ?? [];
  const existing = groups.find((g) => g.brandKey === e.brand);
  if (existing) {
    if (!existing.codes.includes(e.foreign_code)) existing.codes.push(e.foreign_code);
  } else {
    groups.push({ brandKey: e.brand, label: brand.label, codes: [e.foreign_code] });
  }
  BY_TAMIYA_CODE.set(e.tamiya_code, groups);
}

for (const groups of BY_TAMIYA_CODE.values()) {
  groups.sort((a, b) => (BRANDS.get(a.brandKey)?.sort ?? 0) - (BRANDS.get(b.brandKey)?.sort ?? 0));
}

/**
 * Every brand that sells a match for this Tamiya code, in display order —
 * empty when the chart has no row for it, which is common and not an error.
 * Coverage is uneven by line: the bottle ranges are well covered, the TS/AS
 * spray cans barely at all, so a decanted spray usually returns nothing.
 */
export function getEquivalentsFor(tamiyaCode: string): BrandEquivalents[] {
  return BY_TAMIYA_CODE.get(tamiyaCode) ?? [];
}
