import { normalizePaintCode } from "@/domain/paint-code";
import {
  buildPaintSearchIndex,
  searchPaintIndex,
  type SearchablePaint,
} from "@/domain/paint-search";

import catalogueSeed from "../../seed/paints.tamiya.json";

/**
 * The Tamiya catalogue, compiled into the build.
 *
 * `seed/paints.tamiya.json` is generated by `scripts/build-catalogue.ts`,
 * committed, and verified in CI (docs/PLAN.md §2.2) — the same file the `paint`
 * table is seeded from. Reading it here rather than querying that table is a
 * deliberate performance decision (docs/PERFORMANCE.md):
 *
 *   - a code lookup costs a Map hit instead of a Neon HTTP round trip;
 *   - type-ahead search never touches the network, so it answers per keystroke
 *     instead of per network round trip;
 *   - the Thinner Bench can be prerendered, because nothing about a paint's
 *     identity or its family's ratio is request-dependent;
 *   - `next build` stays database-free, which is what CI needs.
 *
 * The `paint` table stays exactly as it is: it's the seed target and the
 * foreign key every user-owned table (inventory, equivalents, requirements)
 * hangs off. This module replaces the *read* path for catalogue identity only.
 */

interface SeedPaint {
  code: string;
  line: string;
  name: string;
  hex: string;
  family: string;
  finish: string | null;
  size_ml: number;
  discontinued: boolean;
  verified_at: string | null;
}

export interface CataloguePaint extends SearchablePaint {
  code: string;
  line: string;
  name: string;
  hex: string;
  family: string;
  finish: string | null;
  sizeMl: number;
  discontinued: boolean;
}

const PAINTS: readonly CataloguePaint[] = (catalogueSeed as SeedPaint[]).map((row) => ({
  code: row.code,
  line: row.line,
  name: row.name,
  hex: row.hex,
  family: row.family,
  finish: row.finish,
  sizeMl: row.size_ml,
  discontinued: row.discontinued,
}));

const BY_CODE = new Map(PAINTS.map((row) => [row.code, row]));
const INDEX = buildPaintSearchIndex(PAINTS);

/** Accepts anything the user might type — "xf64", "XF 64" — not just "XF-64". */
export function getCataloguePaint(code: string): CataloguePaint | undefined {
  return BY_CODE.get(normalizePaintCode(code));
}

export function searchCatalogue(query: string, limit = 8): CataloguePaint[] {
  return searchPaintIndex(INDEX, query, limit);
}

export const CATALOGUE_SIZE = PAINTS.length;
